"""
C-Pure Compiler Parser (LL(1) + SDT)
-----------------------------------

Authors:
    Team 7:
    - Alvarez Salgado Eduardo Antonio
    - González Vázquez Alejandro
    - Jiménez Olivo Evelin
    - Lara Hernández Emmanuel
    - Parra Fernández Héctor Emilio

Date:
    April 30, 2026

Program description:
The Parser class implements a predictive recursive-descent parser with
Syntax-Directed Translation (SDT) capabilities for a simplified C-like language.

It processes a list of tokens generated by the lexical analyzer and builds
an Abstract Syntax Tree (AST) while performing semantic analysis using a
symbol table.

Responsibilities:
- Validate syntax using a top-down LL(1)-style recursive descent approach.
- Construct an Abstract Syntax Tree (AST).
- Perform semantic analysis (declarations, scope, initialization tracking).
- Maintain a symbol table with scope management.
- Detect semantic and syntactic errors.
- Generate derivation/logging steps for debugging and reporting.

Features:
- Supports global declarations (variables, functions, classes).
- Supports local variable declarations and assignments.
- Function declarations with scoped symbol tables.
- Expression parsing with recursive descent structure.
- Print statements (`writeln`).
- Class declarations with nested global members.
- Semantic validation:
    - Duplicate variable detection
    - Initialization tracking
    - Scope handling for functions
- AST generation using ASTNode structure.
"""

from Ast.ASTNode import ASTNode
from Semantic.SymbolTable import SymbolTable


class Parser:
    """
    Recursive Descent Parser with Syntax-Directed Translation (SDT).

    This class processes a token stream and constructs an AST while
    performing semantic checks using a symbol table.

    Attributes
    ----------
    tokens : list
        List of tokens produced by the lexer.
    current : int
        Current position in the token stream.
    symbol_table : SymbolTable
        Manages identifiers, scopes, and semantic validation.
    current_function_type : str | None
        Stores return type of the function being parsed.
    sdt_errors : list
        List of semantic or syntactic errors detected during parsing.
    derivation : list
        Step-by-step derivation trace for debugging or reporting.
    """

    TYPE_KEYWORDS = {"int", "float", "double", "char", "void", "string"}

    def __init__(self, tokens_list):
        """
        Initialize parser and validate lexical correctness.

        Parameters
        ----------
        tokens_list : list
            Tokens generated by the lexical analyzer.

        Raises
        ------
        Exception
            If an unknown token is found.
        """

        # Lexical validation
        unknown_tokens = [t for t in tokens_list if t["type"] == "Unknown"]
        if unknown_tokens:
            first_err = unknown_tokens[0]
            raise Exception(
                f"[Line {first_err['line']}] Lexical Error: Unknown token '{first_err['value']}'"
            )

        self.tokens = tokens_list
        self.current = 0

        # Semantic structures
        self.symbol_table = SymbolTable()
        self.current_function_type = None

        self.sdt_errors = []
        self.derivation = []

    def log(self, msg):
        """Store a derivation step for reporting."""
        self.derivation.append(msg)

    def error(self, msg):
        """Register a semantic or syntactic error."""
        self.sdt_errors.append(f"[Line {self.peek()['line']}] {msg}")

    def peek(self):
        """Return current token without consuming it."""
        if self.current < len(self.tokens):
            return self.tokens[self.current]
        return {"type": "EOF", "value": "$", "line": -1}

    def advance(self):
        """Consume and return the current token."""
        if self.current < len(self.tokens):
            self.current += 1
        return self.tokens[self.current - 1]

    def match(self, val):
        """Match token by value."""
        if self.peek()["value"] == val:
            self.advance()
            return True
        return False

    def match_type(self, t):
        """Match token by type."""
        if self.peek()["type"] == t:
            return self.advance()
        return None

    def consume(self, val, msg):
        """Consume expected token by value or raise error."""
        if self.peek()["value"] == val:
            return self.advance()
        raise Exception(f"[Line {self.peek()['line']}] {msg}")

    def consume_type(self, t, msg):
        """Consume expected token by type or raise error."""
        if self.peek()["type"] == t:
            return self.advance()
        raise Exception(f"[Line {self.peek()['line']}] {msg}")

    def is_at_end(self):
        """Check if parsing reached EOF."""
        return self.peek()["type"] == "EOF"

    def parse_program(self):
        """PROGRAM -> Declaration*"""
        self.log("Program -> Declaration*")

        nodes = []
        while not self.is_at_end():
            nodes.append(self.parse_global())

        return ASTNode("PROGRAM", nodes)

    def parse_global(self):
        """Parse global declarations (class, function, variable)."""
        token = self.peek()

        if token["value"] == "class":
            return self.parse_class()

        type_token = token["value"]
        self.advance()
        id_token = self.consume_type("Identifiers", "Expected identifier")

        if self.peek()["value"] == "(":
            return self.parse_function(type_token, id_token)

        return self.parse_global_var(type_token, id_token)

    def parse_class(self):
        """class Identifier { Declaration* }"""
        self.consume("class", "Expected class")
        id_token = self.consume_type("Identifiers", "Expected identifier")

        self.log("ClassDeclaration -> class Identifier { Declaration* }")
        self.log(f"Identifier -> {id_token['value']}")

        self.consume("{", "Expected '{'")

        body = []
        while self.peek()["value"] != "}":
            body.append(self.parse_global())

        self.consume("}", "Expected '}'")

        return ASTNode("CLASS", body, value=id_token["value"])

    def parse_global_var(self, t, id_token):
        """Global variable declaration with optional initialization."""
        self.log("VariableDeclaration -> Datatype Identifier ['=' Expression] ';'")
        self.log(f"Datatype -> {t}")
        self.log(f"Identifier -> {id_token['value']}")

        if not self.symbol_table.declare(id_token["value"], t, id_token["line"]):
            self.error(f"Duplicate variable '{id_token['value']}'")

        children = []

        if self.match("="):
            expr = self.parse_expression()
            children.append(expr)
            self.symbol_table.mark_as_initialized(id_token["value"])

        self.consume(";", "Expected ';'")

        return ASTNode("GLOBAL_VAR", children, value=id_token["value"], inferred_type=t)

    def parse_function(self, t, id_token):
        """Function declaration with no parameters."""
        self.log("FunctionDeclaration -> function Datatype Identifier () { Statement* }")

        self.consume("(", "Expected '('")
        self.consume(")", "Expected ')'")

        self.consume("{", "Expected '{'")

        self.symbol_table.enter_scope()
        self.current_function_type = t

        body = []
        while self.peek()["value"] != "}":
            body.append(self.parse_statement())

        self.consume("}", "Expected '}'")

        self.symbol_table.exit_scope()
        self.current_function_type = None

        return ASTNode("FUNCTION", body, value=id_token["value"], inferred_type=t)

    def get_derivation(self, ast=None):
        """Generate derivation trace, AST and semantic report."""
        report = []

        report.append("Derivation Steps:\n")
        report.extend(self.derivation)

        report.append("\nAST:")
        report.append(str(ast) if ast else "(No AST)")

        all_errors = self.sdt_errors + self.symbol_table.errors

        if all_errors:
            report.append("\nSEMANTIC ERRORS:")
            report.extend(all_errors)
        else:
            report.append("\nSEMANTIC STATUS: Verified")

        return "\n".join(report)