"""
Authors:
    Team 7:
    - Alvarez Salgado Eduardo Antonio
    - González Vázquez Alejandro
    - Jiménez Olivo Evelin
    - Lara Hernández Emmanuel
    - Parra Fernández Héctor Emilio

Program description:
This module is responsible for generating and configuring the graphical user
interface of the C-Pure Compiler.

The GUI allows the user to enter source code manually, execute the compiler,
visualize lexical analysis results, verify syntactic and semantic analysis,
and display the generated Abstract Syntax Tree (AST).

Responsibilities:
- Create the main graphical window for the compiler
- Receive and process source code input
- Execute lexical analysis using the Lexer module
- Perform syntactic and semantic analysis using the Parser (SDT)
- Display lexical tokens, derivation steps, and semantic results
- Render and visualize the AST generated by Graphviz
"""

import tkinter as tk
from tkinter import messagebox
from pathlib import Path

from PIL import Image, ImageTk

from Lexer.lexer import Lexer
from Parser.parser_sdt import Parser
from Ast.ast_visualizer import render_ast


# Style configuration for GUI appearance
BG_COLOR = "#121212"
CARD_COLOR = "#1e1e1e"
TEXT_BG = "#0f0f0f"
TEXT_FG = "#f5f5f5"
ACCENT = "#2d7ff9"
BORDER = "#333333"
LEXEME_COLOR = "#a64d59"


lexer_results = []
parser_derivation = ""
ast_image_reference = None


def run_gui():
    """
    Initializes and runs the graphical interface of the compiler.

    The function builds the GUI layout, defines event handlers, and manages
    the full compilation pipeline:
    lexical analysis → parsing → SDT validation → AST generation.
    """

    global lexer_results, parser_derivation, ast_image_reference

    root = tk.Tk()
    root.title("C-Pure Compiler - Team 7")
    root.geometry("1100x900")
    root.configure(bg=BG_COLOR)

    resource_dir = Path(__file__).parent / "resources"
    output_dir = Path(__file__).parent / "output"
    output_dir.mkdir(exist_ok=True)

    text_font = ("Courier New", 11)

    def show_output():
        """
        Displays output based on selected mode:
        0 → Lexical analysis (tokens)
        1 → Parsing + SDT derivation
        2 → AST message
        """

        output_text.config(state=tk.NORMAL)
        output_text.delete("1.0", tk.END)

        mode = view_mode.get()

        # Lexical analysis output
        if mode == 0:
            for token in lexer_results:
                output_text.insert(tk.END, f"[{token['value']}]", "lexeme")
                output_text.insert(
                    tk.END,
                    f" - {token['type']} at line {token['line']}, col {token['column']}\n"
                )

            output_text.tag_config("lexeme", foreground=LEXEME_COLOR)

        # Parser + SDT output
        elif mode == 1:
            output_text.insert(tk.END, parser_derivation)

        # AST message
        elif mode == 2:
            output_text.insert(
                tk.END,
                "AST visualization generated below.\n"
                "Run the compiler if no image is shown.\n"
            )

        output_text.config(state=tk.DISABLED)

    def show_ast_image(image_path):
        """
        Loads and displays the generated AST image in the GUI.
        """

        global ast_image_reference

        try:
            image = Image.open(image_path)

            image.thumbnail((900, 350))

            ast_image_reference = ImageTk.PhotoImage(image)

            ast_label.config(image=ast_image_reference)
            ast_label.image = ast_image_reference

        except Exception as error:
            ast_label.config(image="")
            messagebox.showerror(
                "AST Visualization Error",
                f"Could not display AST image:\n{error}"
            )

    def analyze_text():
        """
        Executes the full compilation pipeline:
        lexical analysis, parsing, SDT validation, and AST generation.
        """

        global lexer_results, parser_derivation

        text = input_text.get("1.0", tk.END).strip()

        if not text:
            messagebox.showwarning("Warning", "Please enter source code first.")
            return

        try:
            # Lexical analysis phase
            lexer = Lexer(text.split("\n"), str(resource_dir))
            lexer_results = lexer.tokenize()

            unknown_tokens = [t for t in lexer_results if t["type"] == "Unknown"]

            if unknown_tokens:
                errors = "\n".join(
                    f"Unknown token '{t['value']}' at line {t['line']}, col {t['column']}"
                    for t in unknown_tokens
                )

                parser_derivation = "Lexical Error...\n\n" + errors

                ast_label.config(image="")
                show_output()

                messagebox.showerror("Lexical Error", errors)
                return

            # Parsing + SDT phase
            parser = Parser(lexer_results)
            ast = parser.parse_program()

            semantic_errors = parser.sdt_errors + parser.symbol_table.errors

            if semantic_errors:
                parser_derivation = "SDT Error...\n\n" + "\n".join(semantic_errors)
                messagebox.showwarning("SDT Error", "Semantic validation failed")
            else:
                parser_derivation = "Parsing Success!\nSDT Verified!"
                messagebox.showinfo("Success", "Compilation successful")

            parser_derivation = parser.get_derivation(ast)

            # AST generation
            ast_path = output_dir / "ast_output"
            image_path = render_ast(ast, str(ast_path), "png")

            show_ast_image(image_path)
            show_output()

        except Exception as error:
            parser_derivation = f"Parsing Error...\n{error}"

            ast_label.config(image="")
            show_output()

            messagebox.showerror("Parsing Error", str(error))

    # ---------------- GUI Layout ----------------

    wrapper = tk.Frame(root, bg=BG_COLOR)
    wrapper.pack(fill="both", expand=True, padx=20, pady=20)

    input_card = tk.Frame(wrapper, bg=CARD_COLOR, highlightbackground=BORDER, highlightthickness=1)
    input_card.pack(fill="both", expand=True, pady=(0, 10))

    tk.Label(input_card, text="Source Code Input", font=("Arial", 12, "bold"),
             bg=CARD_COLOR, fg=TEXT_FG).pack(anchor="w", padx=15, pady=10)

    input_text = tk.Text(input_card, height=10, font=text_font,
                         bg=TEXT_BG, fg=TEXT_FG, insertbackground=TEXT_FG)
    input_text.pack(fill="both", expand=True, padx=15, pady=10)

    tk.Button(wrapper, text="RUN COMPILER", command=analyze_text,
              bg=ACCENT, fg="white", font=("Arial", 10, "bold")).pack(anchor="w")

    view_mode = tk.IntVar(value=0)

    selector = tk.Frame(wrapper, bg=BG_COLOR)
    selector.pack(fill="x", pady=10)

    tk.Radiobutton(selector, text="Lexical", variable=view_mode, value=0,
                   command=show_output, bg=BG_COLOR, fg=TEXT_FG).pack(side="left")

    tk.Radiobutton(selector, text="Parsing", variable=view_mode, value=1,
                   command=show_output, bg=BG_COLOR, fg=TEXT_FG).pack(side="left")

    tk.Radiobutton(selector, text="AST", variable=view_mode, value=2,
                   command=show_output, bg=BG_COLOR, fg=TEXT_FG).pack(side="left")

    output_text = tk.Text(wrapper, height=12, bg=TEXT_BG, fg=TEXT_FG, state=tk.DISABLED)
    output_text.pack(fill="both", expand=True, padx=15, pady=10)

    ast_label = tk.Label(wrapper, bg=TEXT_BG)
    ast_label.pack(fill="both", expand=True, padx=15, pady=10)

    root.mainloop()


if __name__ == "__main__":
    run_gui()